In [6]:
import numpy as np
import pandas as pd

### I. Numerical Computing with NumPy.
#### 1. Array Creation & Basic Operations

In [73]:
#A. Task: Create a 1D array of 10 random integers. Create a 3x3 identity matrix.
arr = np.random.randint(10, 100, 10)
print(arr)
identity_matrix = np.identity(3)
print(identity_matrix)

[13 99 33 24 87 32 95 99 70 83]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [75]:
#B. Task: Multiply the 1D array by a scalar value without using any for loops.
print(arr*10)

[130 990 330 240 870 320 950 990 700 830]

In [76]:
#C. Task: Create two 3x3 matrices. Perform both element-wise multiplication and the dot product.
matrix_1 = np.array([[1, 2, 3],
            [3, 2, 1],
            [7, 6, 9]])

matrix_2 = np.array([[2, 2, 2],
            [3, 3, 3],
            [10, 10, 10]])

print(matrix_1*matrix_2)
print(np.dot(matrix_1, matrix_2))

[[ 2  4  6]
 [ 9  6  3]
 [70 60 90]]
[[ 38  38  38]
 [ 22  22  22]
 [122 122 122]]

#### 2. Statistical Methods

In [77]:
#A. Task: Generate an array of 100 random numbers from a normal distribution.
arr = np.random.randn(100)
arr

array([ 5.53006856e-01, -3.43540109e-01, -6.46639014e-05,  3.62287259e-01,
       -9.52693021e-01, -5.72606199e-01, -1.76765007e-01,  2.35670473e+00,
       -1.51797943e+00,  1.84663357e-02, -1.51206055e-02, -1.65261211e-01,
       -2.26912796e+00,  1.45624274e+00, -5.82321349e-02, -6.18803893e-02,
        3.88947852e-01, -2.43776864e-01,  6.29755453e-01, -4.25825728e-02,
        1.32205953e+00,  2.11375154e+00,  1.52307914e+00, -1.66104388e-01,
       -1.08047402e-02,  1.41587724e+00,  4.27910032e-02,  1.16339280e+00,
        3.56861970e-01,  8.10203934e-01,  4.34104234e-03, -3.01287039e-01,
        4.86706043e-01, -2.15676620e+00,  5.05458490e-01,  1.22247545e-01,
        8.65381312e-01, -1.68904384e+00, -3.37717352e-01,  5.73097853e-01,
       -7.81997915e-01, -8.89236839e-01, -4.41913501e-02,  2.04266305e+00,
        1.85958347e+00, -4.48864014e-01,  5.73889877e-01, -1.06172424e+00,
        2.39913250e-01, -9.33694620e-01, -1.73303277e-01, -6.67335210e-01,
        1.25037661e+00, -1.10943903e+00, -1.56281634e+00,  1.95874612e+00,
        2.00938157e-01,  1.22180045e-01, -1.96666605e+00,  1.80266442e+00,
        5.66352791e-01, -2.76595808e-01, -1.85639705e-01,  1.37585820e+00,
        4.06170980e-01, -8.96726605e-01,  7.31689085e-01, -5.45281169e-01,
        1.04572627e+00,  1.14458394e+00, -1.23575372e+00, -7.49364025e-01,
        5.38043608e-01, -4.76029781e-01, -6.17534332e-01, -9.29801885e-01,
       -1.49512311e+00, -1.78972940e+00, -4.47479388e-01, -7.41603318e-01,
        2.51375598e-01, -6.74489272e-01, -1.48673664e+00, -5.14058392e-02,
       -2.17736645e-01,  7.14256090e-01, -9.28858435e-01, -7.75025928e-01,
       -8.73989351e-01,  4.19538772e-01, -7.12617469e-01,  8.65064628e-01,
        2.97825122e-02, -1.73186127e+00,  2.61124089e+00,  1.01051797e+00,
        9.15783076e-01, -6.30320292e-01,  3.41853405e-01, -7.14828201e-01])

In [78]:
# B. Task: Calculate and print the mean, median, standard deviation, and variance of the array. Find the index of the maximum value.
mean = np.mean(arr)
median = np.median(arr)
standard_deviation = np.std(arr)
variance = np.var(arr)
max_index = np.argmax(arr)
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {standard_deviation}")
print(f"Variance: {variance}")
print(f"Max Index: {max_index}")

Mean: 0.0018429928547397945
Median: -0.043386961439772574
Standard Deviation: 1.0205865945858257
Variance: 1.0415969970482926
Max Index: 94

### II. Tabular Data with Pandas
#### 1. Series

In [79]:
#A. Task: Create a Series object
series = pd.Series([0, -1, 4, -3, 2])
print(series)

0    0
1   -1
2    4
3   -3
4    2
dtype: int64

In [80]:
#B. Task: Modify data in the Series (only single value, and all values)
series[1] *= -1
print(series)

series += 10
print(series)

0    0
1    1
2    4
3   -3
4    2
dtype: int64
0    10
1    11
2    14
3     7
4    12
dtype: int64

In [81]:
#C. Task: Modify index of the Series
series.index = [f"Index: {-i}" for i in range(len(series))]
print(series)

Index: 0     10
Index: -1    11
Index: -2    14
Index: -3     7
Index: -4    12
dtype: int64

#### 2. DataFrames

In [146]:
#A. Task: Create a Pandas DataFrame from a Python dictionary.
dict = {
    "A": np.random.randint(1, 100, 10), 
    "T": np.random.randint(1, 100, 10), 
    "C": np.random.randint(1, 100, 10), 
    "G": np.random.randint(1, 100, 10)
    }

dataframe = pd.DataFrame(dict, index=[f"Sequence: {i+1}" for i in range(10)])
dataframe

               A   T   C   G
Sequence: 1   87  67  14  34
Sequence: 2   20   3  20  60
Sequence: 3   34  46  88  81
Sequence: 4   88  68  85  21
Sequence: 5    6  88  67  32
Sequence: 6   19  37  49  85
Sequence: 7   58  82  95  99
Sequence: 8   71  94  24  42
Sequence: 9    1  50  76  79
Sequence: 10  59  37  19  64

In [117]:
#B. Task: Construct a DataFrame from a 2D NumPy array, manually assigning column names (e.g., 'Feature_1', 'Feature_2', 'Target').
array_2d = np.random.randn(3, 4)
df = pd.DataFrame(array_2d, columns = ["Numbers A", "Numbers B", "Numbers C", "Numbers D"])
df

   Numbers A  Numbers B  Numbers C  Numbers D
0  -0.241366  -0.488654  -0.342376  -1.227010
1   1.472675   0.782112   1.275190   1.163700
2   0.503695   0.178709   0.373090  -0.545487

In [222]:
# C. Task: Create own column as sum (or any other result) of using other columns
dataframe["Total length"] = [dataframe.values[i].sum() for i in range(10)]
dataframe

               A   T   C   G  Total length
Sequence: 1   87  67  14  34           404
Sequence: 2   20   3  20  60           206
Sequence: 3   34  46  88  81           498
Sequence: 4   88  68  85  21           524
Sequence: 5    6  88  67  32           386
Sequence: 6   19  37  49  85           380
Sequence: 7   58  82  95  99           668
Sequence: 8   71  94  24  42           462
Sequence: 9    1  50  76  79           412
Sequence: 10  59  37  19  64           358

#### 3. Data Selection and Indexing

In [152]:
#A. Task: Use .loc to select rows based on a specific index label.
dataframe.loc["Sequence: 4"]

A                88
T                68
C                85
G                21
Total length    262
Name: Sequence: 4, dtype: int64

In [159]:
#B. Task: Use .iloc to select the first 5 rows and the last 2 columns of the DataFrame.
dataframe.iloc[:5, 3:]

              G  Total length
Sequence: 1  34           202
Sequence: 2  60           103
Sequence: 3  81           249
Sequence: 4  21           262
Sequence: 5  32           193

In [174]:
#C. Task: Filter the DataFrame to show only rows where 'Feature_1' is greater than a specific threshold.
dataframe[(dataframe["A"]>50) & (dataframe["G"]<60)]

              A   T   C   G  Total length
Sequence: 1  87  67  14  34           202
Sequence: 4  88  68  85  21           262
Sequence: 8  71  94  24  42           231

### III. Independent Practical Task: loading data from a table

In [226]:
df = pd.read_csv("src/boston.csv")
df.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
1,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
2,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
3,0.03237,NaN,2.18,0.0,0.458,6.998,NaN,6.0622,3,NaN,18.7,NaN,2.94,NaN
4,NaN,0.0,2.18,NaN,NaN,NaN,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,NaN,NaN,394.12,5.21,28.7
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,NaN,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9

In [211]:
print(df.dtypes)

CRIM       float64
ZN         float64
INDUS      float64
CHAS         int64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD          int64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
dtype: object

In [227]:
# Statistics on missing values
missing_counts = df.isna().sum()
print(missing_counts)

CRIM       1
ZN         1
INDUS      0
CHAS       1
NOX        1
RM         1
AGE        1
DIS        0
RAD        0
TAX        2
PTRATIO    1
B          1
LSTAT      1
MEDV       1
dtype: int64

In [229]:
# Statistics on duplicates
total_duplicates = df.duplicated().sum()
print(total_duplicates)

6

In [233]:
# General statistics
stats = df.describe()
print(stats)

             CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  505.000000  505.000000  506.000000  505.000000  505.000000  505.000000
mean     3.616803   11.499010   11.149328    0.069307    0.554993    6.274008
std      8.609841   23.310693    6.849668    0.254227    0.115825    0.704245
min      0.009060    0.000000    0.460000    0.000000    0.385000    3.561000
25%      0.083080    0.000000    5.190000    0.000000    0.449000    5.876000
50%      0.251990    0.000000    9.690000    0.000000    0.538000    6.193000
75%      3.678220   12.500000   18.100000    0.000000    0.624000    6.618000
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  505.000000  506.000000  506.000000  504.000000  505.000000  505.000000
mean    68.866139    3.813980    9.575099  409.303571   18.410099  356.724198
std     28.303975    2.118637    8.689546  168.212321    2.181805   91.337204
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000
25%     45.000000    2.100175    4.000000  281.000000   17.000000  375.520000
50%     77.800000    3.207450    5.000000  330.000000   19.000000  391.270000
75%     94.400000    5.287300   24.000000  666.000000   20.200000  396.210000
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000

            LSTAT        MEDV
count  505.000000  505.000000
mean    12.870772   22.455644
std      7.360604    9.184274
min      1.730000    5.000000
25%      7.120000   16.700000
50%     11.450000   21.100000
75%     17.120000   25.000000
max     37.970000   50.000000

In [235]:
#NumPy Integration
tax_array = df['TAX'].to_numpy()
avg_tax = np.nanmean(tax_array)
print(avg_tax)

409.30357142857144