## Остапенко Родіон КС32 
### Практичне завдання 1. Робота з матрицями і таблицями.
#### Варіант 20
#### $aij={(2i+1.75j)}^{1-0.5i}$
#### $n = 4, m = 5$

In [49]:
import numpy as np
import pandas as pd

#### Виконати дії з векторами і матрицями:

In [38]:
# Створити квадратну матрицю (n×n), заповнити її за правилом з таблиці варіантів.
n = 4
m = 5
matrix = np.zeros((n,n))
for i in range(1, n+1):
    for j in range(1, n+1):
        matrix[i-1,j-1] = (2*i + 1.75*j)**(1 - 0.5*i)
matrix

array([[1.93649167, 2.34520788, 2.6925824 , 3.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [0.3592106 , 0.32444284, 0.2981424 , 0.2773501 ],
       [0.1025641 , 0.08695652, 0.0754717 , 0.06666667]])

In [39]:
# Знайти детермінант матриці і обернену до неї матрицю.
det = np.linalg.det(matrix)
inv = np.linalg.inv(matrix)
print("Determinant = ", det)
print("Inverse = ", inv)

Determinant =  2.2459734243845136e-09
Inverse =  [[   -3214.48056081    42327.29384676  -210150.87039618   384022.68537739]
 [   11400.79715617  -149975.94220705   744122.4288602  -1359133.16870455]
 [  -13166.21216381   173024.04389405  -857947.96813291  1566398.18601853]
 [    4979.89556845   -65374.39553375   323976.40966888  -591287.70269137]]

In [40]:
# Задати два вектори з n елементами, заповнені випадковими числами: один – дійсними числами, другий – цілими числами. Обчислити їх суму і добуток.
v1 = np.random.rand(n)
v2 = np.random.randint(1, 100, size=n)
print("Vector 1:", v1)
print("Vector 2:", v2)
print("Summ:", v1 + v2)
print("Product:", v1 * v2)

Vector 1: [0.92217689 0.13570286 0.10247264 0.70899646]
Vector 2: [86 71 62 32]
Summ: [86.92217689 71.13570286 62.10247264 32.70899646]
Product: [79.30721293  9.6349028   6.35330398 22.68788683]

In [48]:
# Задати дві матриці, заповнені випадковими числами: одна розміру n×m, друга – mn. Знайти їх добуток.
matrix_nm = np.random.randint(1, 100, size=n*m).reshape(n,m)
matrix_mn = np.random.randint(1, 100, size=m*n).reshape(m, n)
print("Matrix mxn:", matrix_mn)
print("Matrix nxm:", matrix_nm)
print("Dot product:", matrix_nm @ matrix_mn)

Matrix mxn: [[ 8 71 74 45]
 [74 28 88 53]
 [66 87 66 19]
 [87 22 13 34]
 [32 23 57 40]]
Matrix nxm: [[83 68 57 15  8]
 [21 64 82 37 52]
 [21 55 23 41 85]
 [61 26 42 95 64]]
Dot product: [[11019 13270 16539  9252]
 [15199 12427 16043  9233]
 [12043  7889 13290  9091]
 [15497 12275 14457 10711]]

In [46]:
# Знайти добуток матриць і векторів (розбити на дві пари, для яких можливо виконання операції).
v_n = np.random.randint(1, 100, size=n)
v_m = np.random.randint(1, 100, size=m)
print("Vector n:", v_n)
print("Vector m:", v_m)

Vector n: [70 17 15 56]
Vector m: [26 86 53 79 13]

In [47]:
print(f"Dot product Vector n * Matrix nm: {v_n @ matrix_nm}")
print(f"Dot product Matrix nm * Vector m: {matrix_nm @ v_m}")
print(f"Dot product Vector m * Matrix mn: {v_m @ matrix_mn}")
print(f"Dot product Matrix mn * Vector n: {matrix_mn @ v_n}")

Dot product Vector n * Matrix nm: [12534 13229 11001  2653  5687]
Dot product Matrix nm * Vector m: [16350 10305 12208 14774]
Dot product Vector m * Matrix mn: [ 7360 15989 12373 13589]
Dot product Matrix mn * Vector n: [8986 5731 6619 7570 4481]

#### Виконати дії з таблицями даних:

In [65]:
data = {
    "Назва": [
        "Український католицький університет (УКУ)",
        "Харківський національний економічний університет (ХНЕУ)",
        "Київський національний університет імені Тараса Шевченка",
        "Національний університет «Києво-Могилянська академія»",
        "Одеський національний університет імені І. І. Мечникова",
        "Державний університет телекомунікацій (ДУТ)",
        "Сумський державний університет (СумДУ)",
        "НТУУ «КПІ ім. І. Сікорського»",
        "Львівський національний університет імені Івана Франка",
        "Харківський національний університет радіоелектроніки (ХНУРЕ)",
        "Національний університет «Львівська політехніка»",
        "Дніпровський національний університет імені Олеся Гончара",
        "НТУ «Дніпровська політехніка»",
        "Хмельницький національний університет (ХНУ)",
        "Київський національний економічний університет (КНЕУ)",
    ],
    "Місто": [
        "Львів",
        "Харків",
        "Київ",
        "Київ",
        "Одеса",
        "Київ",
        "Суми",
        "Київ",
        "Львів",
        "Харків",
        "Львів",
        "Дніпро",
        "Дніпро",
        "Хмельницький",
        "Київ",
    ],
    "Рівень англійської": [83, 56, 73, 79, 70, 46, 43, 58, 63, 53, 58, 48, 51, 48, 59],
    "Рейтинг": [9.3, 8.3, 6.7, 8.7, 7.2, 7.9, 7.8, 6.4, 7.1, 6.8, 6.9, 6.4, 7.4, 6.7, 6.3],
    "Середня зарплата": [3700, 2950, 2950, 2650, 2850, 2950, 3000, 3000, 2800, 2950, 2850, 3000, 2700, 2900, 2800]
}

# Сгенеруємо дані для показника працевлаштування випускників у розробці
np.random.seed(42)
data["Працюють у розробці"] = np.random.randint(75, 96, size=15)

df = pd.DataFrame(data)
df

,Назва,Місто,Рівень англійської,Рейтинг,Середня зарплата,Працюють у розробці
0,Український католицький університет (УКУ),Львів,83,9.3,3700,81
1,Харківський національний економічний університет (ХНЕУ),Харків,56,8.3,2950,94
2,Київський національний університет імені Тараса Шевченка,Київ,73,6.7,2950,89
3,Національний університет «Києво-Могилянська академія»,Київ,79,8.7,2650,85
4,Одеський національний університет імені І. І. Мечникова,Одеса,70,7.2,2850,82
5,Державний університет телекомунікацій (ДУТ),Київ,46,7.9,2950,95
6,Сумський державний університет (СумДУ),Суми,43,7.8,3000,81
7,НТУУ «КПІ ім. І. Сікорського»,Київ,58,6.4,3000,93
8,Львівський національний університет імені Івана Франка,Львів,63,7.1,2800,85
9,Харківський національний університет радіоелектроніки (ХНУРЕ),Харків,53,6.8,2950,85
10,Національний університет «Львівська політехніка»,Львів,58,6.9,2850,95
11,Дніпровський національний університет імені Олеся Гончара,Дніпро,48,6.4,3000,78
12,НТУ «Дніпровська політехніка»,Дніпро,51,7.4,2700,82
13,Хмельницький національний університет (ХНУ),Хмельницький,48,6.7,2900,77
14,Київський національний економічний університет (КНЕУ),Київ,59,6.3,2800,95

In [66]:
# Знайти і вивести університети (назву і рейтинг) з рейтинговою оцінкою випускників вищою за 7.0.
df[df["Рейтинг"] > 7.0][["Назва", "Рейтинг"]]

                                                      Назва  Рейтинг
0                 Український католицький університет (УКУ)      9.3
1   Харківський національний економічний університет (ХНЕУ)      8.3
3     Національний університет «Києво-Могилянська академія»      8.7
4   Одеський національний університет імені І. І. Мечникова      7.2
5               Державний університет телекомунікацій (ДУТ)      7.9
6                    Сумський державний університет (СумДУ)      7.8
8    Львівський національний університет імені Івана Франка      7.1
12                            НТУ «Дніпровська політехніка»      7.4

In [67]:
# Знайти і вивести університети (назву і рівень) з рівнем володіння англійською мовою вищим 50%.
df[df["Рівень англійської"] > 50][["Назва", "Рівень англійської"]]

,Назва,Рівень англійської
0,Український католицький університет (УКУ),83
1,Харківський національний економічний університет (ХНЕУ),56
2,Київський національний університет імені Тараса Шевченка,73
3,Національний університет «Києво-Могилянська академія»,79
4,Одеський національний університет імені І. І. Мечникова,70
7,НТУУ «КПІ ім. І. Сікорського»,58
8,Львівський національний університет імені Івана Франка,63
9,Харківський національний університет радіоелектроніки (ХНУРЕ),53
10,Національний університет «Львівська політехніка»,58
12,НТУ «Дніпровська політехніка»,51
14,Київський національний економічний університет (КНЕУ),59

In [73]:
# Визначити університет, відсоток випускників-розробників якого найвищий.
df[df["Працюють у розробці"] == df["Працюють у розробці"].max()]

,Назва,Місто,Рівень англійської,Рейтинг,Середня зарплата,Працюють у розробці
5,Державний університет телекомунікацій (ДУТ),Київ,46,7.9,2950,95
10,Національний університет «Львівська політехніка»,Львів,58,6.9,2850,95
14,Київський національний економічний університет (КНЕУ),Київ,59,6.3,2800,95

In [76]:
# Знайти і вивести університети, рівень заробітної плати випускників яких нижчий за середній з рейтингу.
mean_salary = df["Середня зарплата"].mean()
print(mean_salary)
df[df["Середня зарплата"] < mean_salary]

2936.6666666666665

,Назва,Місто,Рівень англійської,Рейтинг,Середня зарплата,Працюють у розробці
3,Національний університет «Києво-Могилянська академія»,Київ,79,8.7,2650,85
4,Одеський національний університет імені І. І. Мечникова,Одеса,70,7.2,2850,82
8,Львівський національний університет імені Івана Франка,Львів,63,7.1,2800,85
10,Національний університет «Львівська політехніка»,Львів,58,6.9,2850,95
12,НТУ «Дніпровська політехніка»,Дніпро,51,7.4,2700,82
13,Хмельницький національний університет (ХНУ),Хмельницький,48,6.7,2900,77
14,Київський національний економічний університет (КНЕУ),Київ,59,6.3,2800,95

In [77]:
# Визначити скільки університетів з кожного міста у рейтингу.
df["Місто"].value_counts()

Місто
Київ            5
Львів           3
Харків          2
Дніпро          2
Одеса           1
Суми            1
Хмельницький    1
Name: count, dtype: int64